; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Kepco DTRS Collection"
!define PRODUCT_VERSION "1.1"
!define PRODUCT_PUBLISHER "SecurePoint, Inc."
!define PRODUCT_WEB_SITE ""
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\KCollectionServer.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "Library.nsh"
RequestExecutionLevel admin

Name "${PRODUCT_NAME}"



OutFile "KCollectionServer_setup.exe"
InstallDir "$PROGRAMFILES\SecurePoint\KCollection"
Icon "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
;SilentInstall silent
ShowInstDetails hide
ShowUnInstDetails hide
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""


!define LVM_INSTALLPOS 1127

Section "전체 프로그램 설치" SEC01
  SetOutPath "$INSTDIR"
  KillProcDLL::KillProc "KCollectionServer.exe"
  Sleep 500
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File ".\bin\KCollectionServer.exe"
  File ".\bin\libmariadb.dll"
  File ".\bin\icon.ico"
  File ".\bin\config.ini"
  File ".\bin\uninstall.ico"
  CreateDirectory $INSTDIR\info
  CreateDirectory $SYSDIR\EnTmp
  SetOutPath "$SYSDIR\EnTmp"
  File ".\vc_redist.x64.exe"

  SetOutPath "$INSTDIR\info"
  File /r ".\bin\info\*"
  
  SetOverwrite on
  CreateDirectory "$SMPROGRAMS\SecurePoint"
  CreateShortCut "$SMPROGRAMS\SecurePoint\Uninstall.lnk" "$INSTDIR\uninstall.exe"

  CreateShortCut "$DESKTOP\D-TRS Collection Server.lnk" "$INSTDIR\KCollectionServer.exe" "" "$INSTDIR\icon.ico"

  ReadRegStr $0 HKLM "${PRODUCT_DIR_REGKEY}" "Check"
StrCmp $0 "1" nobla 0
    ;Call InstallVCRedist
    ExecWait "$SYSDIR\EnTmp\vc_redist.x64.exe  /q:a /T:$SYSDIR\EnTmp"    
    SetAutoClose true
    
nobla:
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "Check" "1"	
  SetAutoClose true
SectionEnd


Section -AdditionalIcons
  SetOutPath $INSTDIR
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\KCollectionServer.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  Exec $INSTDIR\KCollectionServer.exe
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd


Section Uninstall
  KillProcDLL::KillProc "KCollectionServer.exe"
  Sleep 500
  ;DeleteRegKey  HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  Delete $INSTDIR\*.*
  Delete "$SMPROGRAMS\SecurePoint\*.*"
  RMDir "$SMPROGRAMS\SecurePoint"
  RMDir "$INSTDIR"
  SetAutoClose true
  
SectionEnd


Function InstallVCRedist
    Call CheckVCRedist
    Pop $R0
    StrCmp $R0 "No" 0 +3
    ExecWait "$INSTDIR\vc_redist.x64.exe /q:a"
FunctionEnd


Function CheckVCRedist
   Push $R0
   ClearErrors
   ReadRegDword $R0 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{837b34e3-7c30-493c-8f6a-2b0f04e2912c}" "Version"

   ; if VS 2005+ redist SP1 not installed, install it
   IfErrors 0 VSRedistInstalled
   StrCpy $R0 "No"

VSRedistInstalled:
   Exch $R0
FunctionEnd